"""Evaluate the ML components on the held-out sets and write the report.

    cd backend
    python scripts/evaluate_ml.py                  # print a summary, write docs/ml/evaluation.*
    python scripts/evaluate_ml.py --no-write       # print only

Runs three classification systems over the same held-out messages - the
keyword rules alone, the classifier alone, and the hybrid the service
actually uses - and the real conversation engine over the gold extraction
set. Nothing here touches the database, the mailbox or any model file: it
only measures.

Reproducible: the sets are fixed files, their SHA-256 is recorded in the
report next to the model versions, and no sampling or randomness is involved,
so two runs on unchanged inputs produce byte-identical output.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import sys
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BACKEND_DIR))

from app.ml.evaluation_runner import full_report  # noqa: E402

REPO_ROOT = BACKEND_DIR.parent
REPORT_DIR = REPO_ROOT / "docs" / "ml"
JSON_REPORT = REPORT_DIR / "evaluation.json"
MARKDOWN_REPORT = REPORT_DIR / "evaluation.md"

SYSTEM_LABELS = {
    "rules": "Keyword rules (the baseline)",
    "ml": "Classifier alone",
    "hybrid": "Hybrid (rules first, then the classifier) - what runs",
}


def render_markdown(report: dict) -> str:
    lines = [
        "# ML evaluation",
        "",
        "Generated by `backend/scripts/evaluate_ml.py`. Do not edit by hand.",
        "",
        f"- Classifier: `{report['models']['classifier']['version']}`",
        f"- Embedder: `{report['models']['embedder']['version']}`",
        f"- Extraction: {report['models']['extractor']}",
        "",
        "## Datasets",
        "",
        "| Set | Examples | SHA-256 |",
        "|---|---:|---|",
    ]
    for meta in report["datasets"].values():
        lines.append(f"| `{meta['path']}` | {meta['n']} | `{meta['sha256'][:16]}…` |")

    lines += [
        "",
        "Both are held out: neither is used to train or tune anything.",
        "",
        "## Complaint classification",
        "",
        "Accuracy and macro-F1 count an abstention as the label `unclear`, so a",
        "system that refuses to answer is not rewarded for it. Coverage is how",
        "often the system did answer, and selective accuracy how often those",
        "answers were right.",
        "",
        "| System | Accuracy | Macro-F1 | Coverage | Selective accuracy | ECE |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for system, label in SYSTEM_LABELS.items():
        r = report["classification"][system]
        lines.append(
            f"| {label} | {r['accuracy']:.3f} | {r['macro_f1']:.3f} | "
            f"{r['coverage']['coverage']:.3f} | {r['coverage']['selective_accuracy']:.3f} | "
            f"{r['ece']:.3f} |"
        )

    lines += ["", "### Macro-F1 by language", "", "| System | English | Russian | Arabic |",
              "|---|---:|---:|---:|"]
    for system, label in SYSTEM_LABELS.items():
        by_lang = report["classification"][system]["by_language"]
        lines.append(
            f"| {label} | {by_lang['en']['macro_f1']:.3f} | {by_lang['ru']['macro_f1']:.3f} | "
            f"{by_lang['ar']['macro_f1']:.3f} |"
        )

    hybrid = report["classification"]["hybrid"]
    lines += ["", "### Per class (hybrid)", "",
              "| Class | Support | Precision | Recall | F1 |", "|---|---:|---:|---:|---:|"]
    for label, scores in hybrid["per_class"].items():
        lines.append(
            f"| {label} | {scores['support']} | {scores['precision']:.3f} | "
            f"{scores['recall']:.3f} | {scores['f1']:.3f} |"
        )

    extraction = report["extraction"]
    lines += [
        "",
        "## Field extraction",
        "",
        "Run through the conversation engine, so schema validation and the",
        "evidence check are included. A value counts as correct only if the",
        "field was expected and the value matches.",
        "",
        f"- Precision **{extraction['precision']:.3f}**, recall "
        f"**{extraction['recall']:.3f}**, F1 **{extraction['f1']:.3f}** "
        f"over {extraction['fields_expected']} expected values",
        f"- Messages with every field exactly right: **{extraction['exact_messages']:.3f}**",
        f"- Hallucination rate (values refused for lack of supporting text): "
        f"**{extraction['hallucination_rate']:.3f}**",
        f"- Evidence matched as: {extraction['evidence_methods']}",
        "",
        "| Field | Support | Precision | Recall | F1 |",
        "|---|---:|---:|---:|---:|",
    ]
    for key, scores in extraction["per_field"].items():
        lines.append(
            f"| `{key}` | {scores['support']} | {scores['precision']:.3f} | "
            f"{scores['recall']:.3f} | {scores['f1']:.3f} |"
        )
    lines += ["", "| Language | Support | Precision | Recall | F1 |", "|---|---:|---:|---:|---:|"]
    for language, scores in extraction["by_language"].items():
        lines.append(
            f"| {language} | {scores['support']} | {scores['precision']:.3f} | "
            f"{scores['recall']:.3f} | {scores['f1']:.3f} |"
        )

    lines += [
        "",
        "## How to read this",
        "",
        "The sets are small (hundreds of short messages, written for this",
        "repository) and synthetic. They measure the pipeline and catch",
        "regressions; they are not a claim about accuracy on real customer mail.",
        "",
    ]
    return "\n".join(lines)


def print_summary(report: dict) -> None:
    print("classification (held-out test set)")
    print(f"  {'system':<8} {'accuracy':>9} {'macro-F1':>9} {'coverage':>9} {'sel.acc':>9}")
    for system in SYSTEM_LABELS:
        r = report["classification"][system]
        print(
            f"  {system:<8} {r['accuracy']:>9.3f} {r['macro_f1']:>9.3f} "
            f"{r['coverage']['coverage']:>9.3f} {r['coverage']['selective_accuracy']:>9.3f}"
        )
    e = report["extraction"]
    print("\nextraction (gold set, through the engine)")
    print(f"  precision {e['precision']:.3f}  recall {e['recall']:.3f}  f1 {e['f1']:.3f}")
    print(f"  hallucination rate {e['hallucination_rate']:.3f}  rejected {e['rejected_values']}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--no-write", action="store_true", help="print without writing files")
    args = parser.parse_args()

    report = asyncio.run(full_report())
    print_summary(report)

    if not args.no_write:
        REPORT_DIR.mkdir(parents=True, exist_ok=True)
        # No timestamp in either file: rerunning on unchanged inputs should
        # produce no diff. The dataset hashes and model versions identify a run.
        JSON_REPORT.write_text(
            json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
        )
        MARKDOWN_REPORT.write_text(render_markdown(report), encoding="utf-8")
        print(f"\nwrote {JSON_REPORT.relative_to(REPO_ROOT)} and "
              f"{MARKDOWN_REPORT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
