"""Customer-facing wording must be natural, language-appropriate, and free of
internal system details:

  - invalid-field corrections must not expose the raw schema key (e.g.
    "account_email") or the raw English validation error text (e.g. "Please
    check this value."/"Not a valid email address.") - see
    RuleBasedAIProvider._field_invalid_message / _FIELD_INVALID_PHRASES.
  - the final ticket confirmation must not expose the raw internal
    classification label (e.g. "withdrawal problem") and must instead show
    the actual collected values under natural, localized labels - see
    ConversationEngine.compose_ticket_confirmation /
    RuleBasedAIProvider._FIELD_DISPLAY_LABELS.
  - the ticket reference is numeric-only, generated by TicketService from the
    ticket's own database primary key (never by the AI) - see
    TicketService._make_reference.

None of this changes the underlying deterministic pending-field / invalid-
field workflow (see test_pending_field_context.py and
test_pending_field_invalid_priority.py, which continue to pass unchanged).
"""

from __future__ import annotations

from fastapi.testclient import TestClient

from app.ai.base import InvalidField, ReplyKind, ReplyRequest
from app.ai.providers.rule_based import RuleBasedAIProvider

_WITHDRAWAL_OPENER_AR = (
    "مرحبا، لدي مشكلة في سحب الأموال. طلبت السحب أمس ولكن المال لم يصل إلى حسابي."
)

# Internal schema keys that must never appear verbatim in a customer-facing
# reply, in any language.
_INTERNAL_KEYS = (
    "account_email",
    "user_id",
    "withdrawal_transaction_id",
    "transaction_date",
    "source_wallet_or_account",
    "deposit_method",
    "problem_description",
)

# Raw English validation-error fragments the old implementation used to leak
# straight into every language's correction message.
_RAW_VALIDATION_PHRASES = (
    "Please check this value",
    "Not a valid email address",
    "Must be at least",
    "Not a recognisable date",
)


def send(
    client: TestClient,
    body: str,
    *,
    conversation_id: int | None = None,
    from_addr: str,
    name: str | None = "Jane",
) -> dict:
    payload: dict = {"from_addr": from_addr, "body": body, "customer_name": name}
    if conversation_id is not None:
        payload["conversation_id"] = conversation_id
    resp = client.post("/api/v1/inbox", json=payload)
    assert resp.status_code == 201, resp.text
    return resp.json()


def _assert_clean(reply_body: str) -> None:
    for key in _INTERNAL_KEYS:
        assert key not in reply_body, f"internal key {key!r} leaked into: {reply_body!r}"
    for phrase in _RAW_VALIDATION_PHRASES:
        assert phrase not in reply_body, (
            f"raw validation text {phrase!r} leaked into: {reply_body!r}"
        )


# --------------------------------------------------------------------- A/B/C


def test_a_arabic_invalid_account_email_gets_a_clear_correction(client):
    addr = "a-ar-invalid-email@example.com"
    r1 = send(client, _WITHDRAWAL_OPENER_AR, from_addr=addr)
    cid = r1["conversation"]["id"]
    send(client, "111", conversation_id=cid, from_addr=addr)

    r3 = send(client, "سيلبمنتى@سيل", conversation_id=cid, from_addr=addr)
    assert r3["conversation"]["pending_field"] == "account_email"
    assert r3["is_complete"] is False
    _assert_clean(r3["reply_body"])
    # Natural, specific Arabic correction - not a generic placeholder.
    assert "البريد الإلكتروني" in r3["reply_body"]
    assert "example@example.com" in r3["reply_body"]


def test_b_russian_invalid_account_email_gets_a_clear_correction(client):
    addr = "b-ru-invalid-email@example.com"
    r1 = send(
        client,
        "Здравствуйте, у меня проблема с выводом денег. Деньги не поступили.",
        from_addr=addr,
    )
    cid = r1["conversation"]["id"]
    send(client, "Мой user id: 111.", conversation_id=cid, from_addr=addr)

    r3 = send(client, "Мой email это test@invalid", conversation_id=cid, from_addr=addr)
    assert r3["conversation"]["pending_field"] == "account_email"
    assert r3["is_complete"] is False
    _assert_clean(r3["reply_body"])
    assert "почт" in r3["reply_body"].lower()  # "электронной почты" - natural Russian for email


def test_c_english_invalid_account_email_gets_a_clear_correction(client):
    addr = "c-en-invalid-email@example.com"
    r1 = send(
        client,
        "I cannot withdraw my money and it has been stuck for two days.",
        from_addr=addr,
    )
    cid = r1["conversation"]["id"]
    send(client, "111", conversation_id=cid, from_addr=addr)

    r3 = send(client, "test@invalid", conversation_id=cid, from_addr=addr)
    assert r3["conversation"]["pending_field"] == "account_email"
    assert r3["is_complete"] is False
    _assert_clean(r3["reply_body"])
    assert "email address" in r3["reply_body"].lower()
    assert "example@example.com" in r3["reply_body"]


# ------------------------------------------------------------------------- D


async def test_d_invalid_user_id_correction_is_clear_and_field_specific():
    """Engine-level check (see test_engine_merge.py for the exact invalid
    value) is not enough on its own since the rule-based extractor can't
    normally produce an invalid user_id (any extracted token already
    satisfies its length bounds) - this drives the same phrasing path via
    the reply layer directly, matching what compose_reply produces for an
    invalid user_id regardless of how it became invalid.
    """
    provider = RuleBasedAIProvider()
    request = ReplyRequest(
        kind=ReplyKind.ASK,
        complaint_label="Withdrawal problem",
        customer_name="Jane",
        language_code="ar",
        invalid_fields=[
            InvalidField(key="user_id", label="User ID", error="Must be at least 2 characters.")
        ],
    )
    draft = await provider.compose_reply(request)
    _assert_clean(draft.body)
    assert "رقم المستخدم" in draft.body
    assert "غير صحيح" in draft.body


# ------------------------------------------------------------------------- E


def test_e_invalid_withdrawal_transaction_id_does_not_advance_or_leak_internals(client):
    addr = "e-invalid-txn@example.com"
    r1 = send(client, _WITHDRAWAL_OPENER_AR, from_addr=addr)
    cid = r1["conversation"]["id"]
    send(client, "111", conversation_id=cid, from_addr=addr)
    send(
        client,
        "البريد المرتبط بحسابي هو customer@example.com",
        conversation_id=cid,
        from_addr=addr,
    )

    # "12" fails withdrawal_transaction_id's own min_length=4 validation.
    r4 = send(client, "12", conversation_id=cid, from_addr=addr)
    assert r4["conversation"]["pending_field"] == "withdrawal_transaction_id"
    assert r4["is_complete"] is False
    _assert_clean(r4["reply_body"])
    assert "عملية السحب" in r4["reply_body"]
    assert "غير صحيح" in r4["reply_body"]

    r5 = send(client, "WD-784512963", conversation_id=cid, from_addr=addr)
    assert r5["is_complete"] is True


# ------------------------------------------------------------------------- F


def test_f_invalid_deposit_date_shows_a_format_example(client):
    addr = "f-invalid-date@example.com"
    r1 = send(client, "My deposit never arrived.", from_addr=addr)
    cid = r1["conversation"]["id"]
    send(client, "111", conversation_id=cid, from_addr=addr)
    send(client, "customer@example.com", conversation_id=cid, from_addr=addr)
    send(client, "my Barclays account", conversation_id=cid, from_addr=addr)

    # Month 13 doesn't exist - a genuine validation rejection.
    r4 = send(client, "2026-13-40", conversation_id=cid, from_addr=addr)
    assert r4["conversation"]["pending_field"] == "transaction_date"
    assert r4["is_complete"] is False
    _assert_clean(r4["reply_body"])
    assert "2026-09-08" in r4["reply_body"] or "YYYY-MM-DD" in r4["reply_body"]

    r5 = send(client, "2026-09-05", conversation_id=cid, from_addr=addr)
    assert r5["conversation"]["pending_field"] == "deposit_method"


# --------------------------------------------------------------------- G/H/I


def test_g_final_arabic_confirmation_shows_collected_info_and_numeric_reference(client):
    addr = "g-final-ar@example.com"
    r1 = send(client, _WITHDRAWAL_OPENER_AR, from_addr=addr)
    cid = r1["conversation"]["id"]
    send(client, "111", conversation_id=cid, from_addr=addr)
    send(
        client,
        "البريد المرتبط بحسابي هو customer@example.com",
        conversation_id=cid,
        from_addr=addr,
    )
    r4 = send(client, "رقم العملية هو WD-784512963", conversation_id=cid, from_addr=addr)

    assert r4["is_complete"] is True
    body = r4["reply_body"]
    ref = r4["ticket_reference"]
    assert ref is not None and ref.isdigit()

    assert "111" in body
    assert "customer@example.com" in body
    assert "WD-784512963" in body
    assert "رقم المستخدم" in body
    assert "البريد الإلكتروني" in body
    assert "رقم عملية السحب" in body
    assert ref in body
    assert "withdrawal problem" not in body
    _assert_clean(body)


def test_h_final_english_confirmation_shows_collected_info_and_numeric_reference(client):
    addr = "h-final-en@example.com"
    r1 = send(
        client,
        "I cannot withdraw my money and it has been stuck for two days.",
        from_addr=addr,
    )
    cid = r1["conversation"]["id"]
    send(client, "111", conversation_id=cid, from_addr=addr)
    send(client, "customer@example.com", conversation_id=cid, from_addr=addr)
    r4 = send(client, "WD-784512963", conversation_id=cid, from_addr=addr)

    assert r4["is_complete"] is True
    body = r4["reply_body"]
    ref = r4["ticket_reference"]
    assert ref is not None and ref.isdigit()

    assert "111" in body
    assert "customer@example.com" in body
    assert "WD-784512963" in body
    assert "User ID" in body
    assert "Account email" in body
    assert "Withdrawal transaction number" in body
    assert ref in body
    assert "withdrawal problem" not in body.lower()
    _assert_clean(body)


def test_i_final_russian_confirmation_shows_collected_info_and_numeric_reference(client):
    addr = "i-final-ru@example.com"
    r1 = send(
        client,
        "Здравствуйте, у меня проблема с выводом денег. Деньги не поступили.",
        from_addr=addr,
    )
    cid = r1["conversation"]["id"]
    send(client, "Мой user id: 111.", conversation_id=cid, from_addr=addr)
    send(client, "Мой account email: customer@example.com.", conversation_id=cid, from_addr=addr)
    r4 = send(client, "Мой transaction id: WD-784512963.", conversation_id=cid, from_addr=addr)

    assert r4["is_complete"] is True
    body = r4["reply_body"]
    ref = r4["ticket_reference"]
    assert ref is not None and ref.isdigit()

    assert "111" in body
    assert "customer@example.com" in body
    assert "WD-784512963" in body
    assert "ID пользователя" in body
    assert "Номер транзакции вывода" in body
    assert ref in body
    _assert_clean(body)


# ------------------------------------------------------------------------- J


def test_j_reference_is_numeric_persisted_and_never_invented_by_ai(client):
    addr = "j-reference-integrity@example.com"
    r1 = send(
        client,
        "I cannot withdraw my money and it has been stuck for two days. "
        "User ID: 111. Account email: customer@example.com. Transaction ID: WD-1.",
        from_addr=addr,
    )
    assert r1["is_complete"] is True
    ref = r1["ticket_reference"]
    assert ref is not None
    assert ref.isdigit()
    assert "-" not in ref

    # The exact same reference is returned by the dashboard/API lookup - the
    # AI only ever phrases a reference the service already generated and
    # persisted; it never invents or alters it.
    ticket = client.get(f"/api/v1/tickets/{ref}").json()
    assert ticket["reference"] == ref
    assert ref in r1["reply_body"]

    tickets = client.get("/api/v1/tickets").json()
    assert any(t["reference"] == ref for t in tickets)


def test_j_two_tickets_get_distinct_numeric_references(client):
    r_a = send(
        client,
        "I cannot withdraw my money and it has been stuck for two days. "
        "User ID: 11. Account email: a@example.com. Transaction ID: WD-1.",
        from_addr="j-a@example.com",
    )
    r_b = send(
        client,
        "I cannot withdraw my money and it has been stuck for two days. "
        "User ID: 22. Account email: b@example.com. Transaction ID: WD-2.",
        from_addr="j-b@example.com",
    )
    assert r_a["ticket_reference"].isdigit()
    assert r_b["ticket_reference"].isdigit()
    assert r_a["ticket_reference"] != r_b["ticket_reference"]
