"""add conversation pending_field

Revision ID: feb4f7967417
Revises: 72e20381914f
Create Date: 2026-09-10 03:45:18.311349

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'feb4f7967417'
down_revision: str | None = '72e20381914f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_field', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('pending_field')

    # ### end Alembic commands ###
